### ISSUE TITLE
Несколько вкладок "Operation"

### ISSUE THREAD

**Issue by Polkooo** [TishchenkoAlex/jetti#10]
Можно сделать чтобы вкладка "Operations" открывалась несколько раз одновременно? Приходится выбирать или один список операций, или другой.

**Comment by gimpon** [comment]
@Polkooo пока можно сделать с помощью новой закладки в браузере, например dublicate в chrome:
![image](https://user-images.githubusercontent.com/58661993/72670609-0f7b0c00-3a48-11ea-8b55-86819318712f.png)

**Comment by Polkooo** [comment]
Я знаю как можно "выкрутится". Вопрос был другой - а можно ли сделать вообще?
