### ISSUE TITLE
Кол-во знаков 

### ISSUE THREAD

**Issue by Polkooo** [TishchenkoAlex/jetti#22]
Вопрос от Черкашина Виктория:

ВОПРОС можно сделать ограничение в  Поле "Назначение платежа" документа "Платежное поручение" не  более 210 символов.  приходится в банке руками подгонять.

**Comment by Polkooo** [comment]
Пример для @gimpon OPER-0000079714 oper - С р/с - оплата поставщику

**Comment by gimpon** [comment]
сделать при формировании выписки из реестра
