### ISSUE TITLE
Не верно тянет договор в operation

### ISSUE THREAD

**Issue by Polkooo** [TishchenkoAlex/jetti#30]
В операции - "Из кассы - Возврат кредитов и займов (Контрагент)" не тянет договор кредита-депозита по контрагенту, хотя у этого контрагента он один и его в списке нет:
![image](https://user-images.githubusercontent.com/59931277/72515259-aa18f680-3860-11ea-9953-82a01bfc3781.png)

**Comment by gimpon** [comment]
исправлено
