### ISSUE TITLE
ЗНРС_копейки

### ISSUE THREAD

**Issue by Polkooo** [TishchenkoAlex/jetti#60]
Прошу выводить в задачах у согласующих точную сумму заявки. Сейчас так:
1.Заявка:
![image](https://user-images.githubusercontent.com/59931277/73359872-dd24a680-42b2-11ea-86da-f89e09fcc84d.png)
2.Задача:
![image](https://user-images.githubusercontent.com/59931277/73359905-eca3ef80-42b2-11ea-8ae4-b0818b4b68d3.png)

**Comment by gimpon** [comment]
в новых БП будут копейки

**Comment by Polkooo** [comment]
+
