### ISSUE TITLE
Auto в строке кода УБРАТЬ!

### ISSUE THREAD

**Issue by Polkooo** [TishchenkoAlex/jetti#64]
Если внесения кода - обязательно, прошу убрать слово "auto", дабы не путать людей.

**Comment by Polkooo** [comment]
![image](https://user-images.githubusercontent.com/59931277/73632919-4a975500-466e-11ea-8f78-1191f155e3e1.png)

**Comment by gimpon** [comment]
Это была ошибка, код всегда авто.

**Comment by Polkooo** [comment]
Теперь во всех документах код будет авто.
