### ISSUE TITLE
№ПП в списании

### ISSUE THREAD

**Issue by Polkooo** [TishchenkoAlex/jetti#67]
![image](https://user-images.githubusercontent.com/59931277/73732948-2316ba00-474c-11ea-9e02-2f1e840ea7e0.png)
После загрузки банка хотелось бы в поле  "№ по банку" видеть № платежного поручения.
(ЧИ)

**Comment by gimpon** [comment]
реализовано Хоренко А. (загрузка банков, также заполняется и дата платежа)

**Comment by Polkooo** [comment]
+
