### ISSUE TITLE
Справочники

### ISSUE THREAD

**Issue by Polkooo** [TishchenkoAlex/jetti#7]
Прошу или переименовать справочники для понимания, кто туда входит или пояснить логику и источник внесения.:
![image](https://user-images.githubusercontent.com/59931277/72465186-c3ca2780-37e7-11ea-92ac-e7ff811b0839.png)

**Comment by gimpon** [comment]
@Polkooo менеджеров убрали

**Comment by Polkooo** [comment]
Есть. Закрываю.
